### PR TITLE
Try fixing failing issues with new pandas version (0.23)

### PR DESCRIPTION
**Pull request by awst-baum**
This is my attempt at fixing #136 

These two one-line-changes make the unit tests pass. WARNING: However, I'm not sure if I completely understand what the code is doing and what changed.

My understanding is that the problems come from two errors at two places in the code:

pytesmo/validation_framework/temporal_matchers.py:70
E   KeyError: "[('index', '')] not found in axis"

and

pytesmo/validation_framework/validation.py:270
E   AttributeError: 'Index' object has no attribute 'droplevel'

I guess they occur because Pandas changed the way it creates column names. In the matcher case, the column name is ('index', '') with pandas 0.22 and just 'index' with pandas 0.23. In the validation case, pandas 0.22 produces a MultiIndex while pandas 0.23 produces a simple Index with tuples as column names.

The changes I propose make pytesmo work with pandas 0.23 - but NOT with 0.22 (not downward compatible). To do that, one would have to investigate the column name creation, I guess.

I hope this helps...

### CODE REVIEW

**Comment by cpaulik** [comment]
Thanks. I think it is ok to update our requirement to pandas 0.23. @sebhahn Do you foresee any problems?

Another option would be to check `pandas.__version__` but I'm not sure that is worth it.

**Comment by sebhahn** [comment]
I'd suggest to check `pandas.__version__` since it is not much to change

**Comment by awst-baum** [comment]
Here's my attempt at making the change downward compatible.

**Comment by sebhahn** [comment]
I'm not sure if users are ready to change to the latest pandas version and since pytesmo is more famous among other packages from our group I'd suggest supporting multiple pandas versions at least for some time.

**Comment by awst-baum** [comment]
Whatever you want guys, just make a decision ;-)

**Comment by cpaulik** [comment]
ok. I'll merge this and also fix the python 3.6 test
